### ISSUE TITLE
SEGV on force sensor

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/tiago_metapkg_ros_control_sot#1]
Dear @olivier-stasse 

I get a SEGV because there is no force sensor values set in roscontrol_sot.

I see two workaround, depending on what we want to achieve:
- either remove `forces: forces` below 
https://github.com/stack-of-tasks/tiago_metapkg_ros_control_sot/blob/2fde7d70dc61d470e4592a47a48bbdd5b58658c5/roscontrol_sot_tiago/config/sot_tiago_params_gazebo.yaml#L8
- change the size of related signal in ~~roscontrol_sot_tiago~~ **sot-tiago**.

The second option is likely a bit more robust.

**Comment by olivier-stasse** [comment]
It is probably a problem in sot_tiago

**Comment by jmirabel** [comment]
> It is probably a problem in sot_tiago

You are right. I edited my error. Should we keep the `forces: forces` in the file mentioned ?

**Comment by olivier-stasse** [comment]
Yes we should

**Comment by olivier-stasse** [comment]
@jmirabel Does your PR fix the issue ?

**Comment by jmirabel** [comment]
The SEGV, yes. But there are still some fragile things about force sensors. Many part of the code were implemented for 4 force sensors...

**Comment by olivier-stasse** [comment]
True, one of the problem is that there is no information about force sensors in the URDF.
My plane was to add information in the yaml.
This should go inside the pinocchio-device coupled with a yaml file.
